version: '3.8'

services:
  # Nosso serviço de Backend (FastAPI + LangGraph)
  triage_api:
    build:
      context: .
      dockerfile: api.Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - .env # Injeta a chave do Gemini de forma segura
    networks:
      - ai_network

  # Nosso serviço de Frontend (Streamlit)
  triage_web:
    build:
      context: .
      dockerfile: web.Dockerfile
    ports:
      - "8501:8501"
    environment:
      # O Streamlit vai conversar com a API pelo nome do contêiner na rede interna!
      - API_URL=http://triage_api:8000/api/v1/triage
    depends_on:
      - triage_api
    networks:
      - ai_network

# Define uma rede interna exclusiva para os dois contêineres
networks:
  ai_network:
    driver: bridge